# Site settings
title: Frontend Interview Preparation Guide
description: Comprehensive frontend interview materials for Big Tech companies
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: null  # Using custom theme

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  frontend:
    output: true
    permalink: /:collection/:name/
  leetcode:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "frontend"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "leetcode"
    values:
      layout: "page"

# Syntax highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
  parse_block_html: true

# Liquid configuration
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Include files
include:
  - "*.ts"
  - "*.tsx"
  - "_pages"
  - "assets"

# Exclude files
exclude:
  - "fix*.py"
  - "cleanup*.sh"
  - "fix*.sh"
  - "*.sh"
  - "deployment-verification.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
  - ".sass-cache"
  - ".jekyll-cache"
  - "gemfiles"

# Permalink structure
permalink: pretty

# Reading Files
safe: false
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
show_drafts: null
limit_posts: 0
future: false
unpublished: false

# Conversion
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false