import os

knowledge_files = [  # (path, content)
    ("frontend/algorithms/array.md", """# Array Algorithms\n\n## Key Patterns\n- Sliding Window\n- Two Pointers\n- Prefix Sum\n- Hash Map\n\n## Problem List\n- Two Sum\n- Best Time to Buy and Sell Stock\n- Move Zeroes\n\n## Interview Questions\n- How do you reverse an array in-place?\n- What is the sliding window technique?\n\n## Tips\n- Practice with LeetCode 150\n- Master common patterns\n"""),
    ("frontend/algorithms/string.md", """# String Algorithms\n\n## Key Patterns\n- Sliding Window\n- Hash Map\n- Two Pointers\n\n## Problem List\n- Longest Substring Without Repeating Characters\n- Valid Anagram\n- Palindrome\n\n## Interview Questions\n- How do you check if a string is a palindrome?\n- What is the difference between substring and subsequence?\n\n## Tips\n- Practice with LeetCode 150\n- Focus on edge cases\n"""),
    ("frontend/algorithms/tree-graph.md", """# Tree & Graph Algorithms\n\n## Key Patterns\n- DFS, BFS\n- Recursion\n- Topological Sort\n\n## Problem List\n- Maximum Depth of Binary Tree\n- Validate Binary Search Tree\n- Number of Islands\n\n## Interview Questions\n- What is the difference between BFS and DFS?\n- How do you detect a cycle in a graph?\n\n## Tips\n- Draw diagrams for tree/graph problems\n- Practice recursion\n"""),
    ("frontend/algorithms/linked-list.md", """# Linked List Algorithms\n\n## Key Patterns\n- Fast/Slow Pointer\n- Reversal\n- Cycle Detection\n\n## Problem List\n- Reverse Linked List\n- Merge Two Sorted Lists\n- Linked List Cycle\n\n## Interview Questions\n- How do you detect a cycle in a linked list?\n- How do you reverse a linked list?\n\n## Tips\n- Practice pointer manipulation\n- Draw node diagrams\n"""),
    ("frontend/algorithms/dp.md", """# Dynamic Programming (DP)\n\n## Key Patterns\n- Memoization\n- Tabulation\n- State Transition\n\n## Problem List\n- Climbing Stairs\n- Coin Change\n- Longest Increasing Subsequence\n\n## Interview Questions\n- What is memoization?\n- How do you identify a DP problem?\n\n## Tips\n- Break problems into subproblems\n- Practice with classic DP problems\n"""),
    ("frontend/algorithms/sorting-searching.md", """# Sorting & Searching Algorithms\n\n## Key Patterns\n- Binary Search\n- Merge Sort\n- Quick Sort\n\n## Problem List\n- Merge Sorted Array\n- Search in Rotated Sorted Array\n- Kth Largest Element\n\n## Interview Questions\n- How does binary search work?\n- What is the time complexity of quick sort?\n\n## Tips\n- Know the difference between stable/unstable sorts\n- Practice binary search edge cases\n"""),
    ("frontend/algorithms/backtracking.md", """# Backtracking Algorithms\n\n## Key Patterns\n- Recursion\n- State Tracking\n\n## Problem List\n- Subsets\n- Permutations\n- N-Queens\n\n## Interview Questions\n- What is backtracking?\n- How do you prune the search space?\n\n## Tips\n- Practice with classic backtracking problems\n- Draw recursion trees\n"""),
    ("frontend/algorithms/math.md", """# Math Algorithms\n\n## Key Patterns\n- Prime Numbers\n- GCD/LCM\n- Bit Manipulation\n\n## Problem List\n- Fizz Buzz\n- Count Primes\n- Power of Two\n\n## Interview Questions\n- How do you check if a number is prime?\n- What is bit manipulation?\n\n## Tips\n- Practice with number theory problems\n- Review bitwise operators\n"""),
    ("frontend/algorithms/design.md", """# Design Problems\n\n## Key Patterns\n- OOP\n- Data Structures\n- System Design\n\n## Problem List\n- Min Stack\n- LRU Cache\n- Design Hit Counter\n\n## Interview Questions\n- How do you design a stack with min()?\n- What is a cache and how does LRU work?\n\n## Tips\n- Practice with design patterns\n- Draw class diagrams\n"""),
    ("frontend/algorithms/others.md", """# Other Algorithms\n\n## Key Patterns\n- Stack/Queue\n- Miscellaneous\n\n## Problem List\n- Valid Parentheses\n- Implement Queue using Stacks\n\n## Interview Questions\n- How do you implement a queue using stacks?\n\n## Tips\n- Practice with stack/queue problems\n"""),
    ("frontend/system-design/frontend-architecture.md", """# Frontend Architecture\n\n## Overview\n- Monolith vs Microfrontend\n- SSR, CSR, SSG, ISG\n- CDN, Caching, Performance\n\n## Key Concepts\n- Scalability\n- Metrics\n- Diagram examples\n\n## Interview Questions\n- How do you design a scalable frontend system?\n- What is SSR and when do you use it?\n"""),
    ("frontend/system-design/ssr-csr-ssg-isg.md", """# SSR, CSR, SSG, ISG\n\n## Overview\n- Server Side Rendering (SSR)\n- Client Side Rendering (CSR)\n- Static Site Generation (SSG)\n- Incremental Static Generation (ISG)\n\n## Interview Questions\n- What are the pros and cons of SSR vs CSR?\n- When would you use SSG?\n"""),
    ("frontend/system-design/cdn-caching.md", """# CDN & Caching\n\n## Overview\n- CDN basics\n- Caching strategies\n- Performance optimization\n\n## Interview Questions\n- How does a CDN work?\n- What is cache invalidation?\n"""),
    ("frontend/system-design/performance.md", """# Performance Optimization\n\n## Overview\n- Lazy Loading\n- Code Splitting\n- Bundle Optimization\n\n## Interview Questions\n- How do you optimize frontend performance?\n- What tools do you use for performance profiling?\n"""),
    ("frontend/system-design/microfrontend.md", """# Microfrontend\n\n## Overview\n- Microfrontend architecture\n- Pros and cons\n- Implementation strategies\n\n## Interview Questions\n- What is a microfrontend?\n- How do you share state between microfrontends?\n"""),
    ("frontend/system-design/metrics-scalability.md", """# Metrics & Scalability\n\n## Overview\n- Success metrics\n- Scalability patterns\n- Monitoring\n\n## Interview Questions\n- How do you measure frontend success?\n- What is horizontal scaling?\n"""),
    ("frontend/web-fundamentals/http.md", """# HTTP Fundamentals\n\n## Key Concepts\n- HTTP 1 vs 2 vs 3\n- TCP/IP basics\n- CDN, Caching\n\n## Interview Questions\n- What is the difference between HTTP 1 and HTTP 2?\n- How does CDN improve performance?\n"""),
    ("frontend/web-fundamentals/tcpip.md", """# TCP/IP\n\n## Key Concepts\n- TCP vs UDP\n- Three-way handshake\n- Packet loss\n\n## Interview Questions\n- How does TCP establish a connection?\n- What is the difference between TCP and UDP?\n"""),
    ("frontend/web-fundamentals/cdn.md", """# CDN\n\n## Key Concepts\n- What is a CDN?\n- How does it work?\n- Benefits for frontend\n\n## Interview Questions\n- How does a CDN reduce latency?\n- What are the tradeoffs of using a CDN?\n"""),
    ("frontend/web-fundamentals/caching.md", """# Caching\n\n## Key Concepts\n- Browser cache\n- CDN cache\n- Cache-Control headers\n\n## Interview Questions\n- What is cache invalidation?\n- How do you control cache in HTTP?\n"""),
    ("frontend/web-fundamentals/browser-rendering.md", """# Browser Rendering\n\n## Key Concepts\n- Critical rendering path\n- Reflow vs repaint\n- Layout, paint, composite\n\n## Interview Questions\n- What is the critical rendering path?\n- How do browsers optimize rendering?\n"""),
    ("frontend/web-fundamentals/event-loop.md", """# Event Loop\n\n## Key Concepts\n- Call stack\n- Callback queue\n- Microtasks vs macrotasks\n\n## Interview Questions\n- How does the JS event loop work?\n- What is the difference between microtask and macrotask?\n"""),
    ("frontend/web-fundamentals/js-engine.md", """# JavaScript Engine\n\n## Key Concepts\n- V8, SpiderMonkey, JavaScriptCore\n- JIT compilation\n- Garbage collection\n\n## Interview Questions\n- What is JIT compilation?\n- How does garbage collection work in JS?\n"""),
    ("frontend/web-fundamentals/security.md", """# Web Security\n\n## Key Concepts\n- XSS, CSRF\n- CORS\n- HTTPS\n\n## Interview Questions\n- What is XSS?\n- How do you prevent CSRF?\n"""),
    ("frontend/web-fundamentals/networking.md", """# Networking\n\n## Key Concepts\n- REST, GraphQL\n- WebSockets\n- API integration\n\n## Interview Questions\n- What is the difference between REST and GraphQL?\n- How do WebSockets work?\n"""),
    ("frontend/react-js-ts/hooks.md", """# React Hooks\n\n## Key Concepts\n- useState\n- useEffect\n- useRef\n- useContext\n\n## Interview Questions\n- How does useEffect work?\n- What is the difference between useRef and useState?\n"""),
    ("frontend/react-js-ts/context.md", """# React Context\n\n## Key Concepts\n- Context API\n- Provider/Consumer\n- useContext\n\n## Interview Questions\n- When should you use React Context?\n- How do you avoid prop drilling?\n"""),
    ("frontend/react-js-ts/use-effect.md", """# useEffect\n\n## Key Concepts\n- useEffect vs useLayoutEffect\n- Cleanup functions\n- Dependency array\n\n## Interview Questions\n- What is the difference between useEffect and useLayoutEffect?\n- How do you prevent infinite loops in useEffect?\n"""),
    ("frontend/react-js-ts/use-ref.md", """# useRef\n\n## Key Concepts\n- Mutable refs\n- Accessing DOM nodes\n- Persisting values\n\n## Interview Questions\n- When should you use useRef?\n- How do you use useRef to access a DOM element?\n"""),
    ("frontend/react-js-ts/performance.md", """# React Performance\n\n## Key Concepts\n- Memoization\n- useMemo, useCallback\n- React.memo\n\n## Interview Questions\n- How do you optimize React performance?\n- What is memoization?\n"""),
    ("frontend/react-js-ts/patterns.md", """# React Patterns\n\n## Key Concepts\n- Compound components\n- Render props\n- Higher-order components\n\n## Interview Questions\n- What is a compound component?\n- How do you use render props?\n"""),
    ("frontend/react-js-ts/typescript.md", """# TypeScript for React\n\n## Key Concepts\n- Type safety\n- Generics\n- Interfaces\n\n## Interview Questions\n- How do you type React props with TypeScript?\n- What are generics in TypeScript?\n"""),
    ("frontend/behavioral/team-management.md", """# Team Management & Leadership\n\n## Key Topics\n- Success Metrics\n- Performance Review\n- Career Growth\n- Conflict Resolution\n\n## Interview Questions\n- How do you evaluate team member performance?\n- How do you resolve conflicts in your team?\n"""),
    ("frontend/behavioral/success-metrics.md", """# Success Metrics\n\n## Key Concepts\n- Defining success\n- Measuring outcomes\n- KPIs\n\n## Interview Questions\n- How do you define success for a project?\n- What metrics do you track?\n"""),
    ("frontend/behavioral/performance-review.md", """# Performance Review\n\n## Key Concepts\n- Feedback\n- Evaluation\n- Growth plans\n\n## Interview Questions\n- How do you conduct a performance review?\n- How do you give constructive feedback?\n"""),
    ("frontend/behavioral/career-growth.md", """# Career Growth\n\n## Key Concepts\n- Promotion\n- Skill development\n- Mentorship\n\n## Interview Questions\n- How do you help team members grow?\n- What is your approach to mentorship?\n"""),
    ("frontend/behavioral/conflict-resolution.md", """# Conflict Resolution\n\n## Key Concepts\n- Identifying conflict\n- Mediation\n- Resolution strategies\n\n## Interview Questions\n- How do you handle conflict in a team?\n- What is your approach to mediation?\n"""),
    ("frontend/behavioral/product-management.md", """# Product Management\n\n## Key Concepts\n- Product lifecycle\n- Stakeholder management\n- Roadmapping\n\n## Interview Questions\n- How do you prioritize features?\n- How do you manage stakeholders?\n"""),
    ("frontend/interview-strategy/checklist.md", """# Interview Preparation Checklist\n\n## Before Interview\n- Update CV\n- Research company/team\n- Practice coding patterns\n\n## During Interview\n- Communicate clearly\n- Ask clarifying questions\n\n## After Interview\n- Follow up with HR\n- Reflect and improve\n"""),
    ("frontend/interview-strategy/real-interview-stories.md", """# Real Interview Stories\n\n## Example: TikTok Singapore Frontend Interview\n- 3 technical rounds (coding, system design, frontend, behavioral)\n- 1 manager round, 1 HR round\n- See detailed experience in the blog section\n\n## Lessons Learned\n- Never underestimate any round\n- Prepare for both technical and behavioral\n- Always follow up and reflect\n"""),
    ("frontend/interview-strategy/deal-negotiation.md", """# Deal & Negotiation\n\n## Key Concepts\n- Salary negotiation\n- Benefits\n- Offer comparison\n\n## Interview Questions\n- How do you negotiate an offer?\n- What benefits are most important to you?\n"""),
    ("frontend/interview-strategy/mindset.md", """# Interview Mindset\n\n## Key Concepts\n- Growth mindset\n- Handling failure\n- Staying motivated\n\n## Tips\n- Learn from every interview\n- Don't be afraid to fail\n"""),
    ("frontend/interview-strategy/resources.md", """# Interview Resources\n\n## Key Resources\n- Grokking Coding Interview Patterns\n- Frontend Interview Handbook\n- Great Frontend\n- LeetCode 150\n"""),
    ("frontend/mindmap.md", """# Frontend Interview Mindmap\n\n![Mindmap Frontend Prep](assets/images/frontend-mindmap.png)\n\n> This mindmap summarizes all key areas for frontend interview preparation. Click on each branch in the knowledge map to explore detailed content.\n""")
]

for path, content in knowledge_files:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Created: {path}") 